### PR TITLE
Use static `IAsyncOperationCompletedHandlerWrapper`

### PR DESCRIPTION
**Pull request by german-one**
I admit that I don't particularly like it. Returning a pointer to a static object has a smell.  
Furthermore I just hope that it is technically good enough as I don't have any insight into the implementation of the undocumented interface.  
  
<br>  
However, I found it worth proposing as it removes both heap allocation and reference counting.

### CODE REVIEW

**Comment by lhecker** [comment]
Hmm... This change may be a little bit too risky, especially given that the code isn't really a hot path either. The wrapper is used asynchronously in a background thread by COM, so assuming that there can only be a single instance of it at any given time? I... don't know... Too risky?

**Comment by german-one** [comment]
The "Use current location" button is disabled as long as the position is not yet found, right? Could the settings callback even receive onother `IDC_GEOLOCATION_USE_CURRENT` that would lead to crate another instance meanwhile? I think it can't which is the reason why I considered a static wrapper an opportunity. I don't mind closing this, though 😅

**Comment by lhecker** [comment]
That's true, but the code that prevents the concurrent request is in another file (the UI code). This would make the dependency implicit across "components".
Another big reason I think the safer approach is beneficial, is because it allows me (and you & anyone else), to simply copy the wrapper into another C project that uses WinRT as-is and it'll just work. 🙂

**Comment by german-one** [comment]
I mean, we both don't really like this. I agree that the code isn't a hot path, I agree that the original code is a good example of how to implement the interface. I think we'd also agree that the update is quite subtle and potentially not robust enough to survive any further update in this area anyway. So no good reason to prevent it from throwing into the trash can 😄

**Comment by german-one** [comment]
There's one thing that I forgot to ask.  
`geolocation_callback()` begins with a condition that causes a deadlock of the asynchronous thread if the location service is disabled (Start  > Settings  > Privacy & security > Location). That's because besides `Started`, also `Canceled` and `Error` are != `Completed`. Is that intended? It makes that the "Use current location" button keeps being disabled. Perhaps this is not too bad after all.  

https://github.com/lhecker/windows-dark-mode-switcher/blob/cfdd8a93935ca78e81fec5ba5648f1f26b0afcb1/src/settings.c#L188C1-L191C1

**Comment by lhecker** [comment]
Oh, hmm, that's a situation I haven't tested. I'll see if I can fix it by showing a `MessageBox` or something.

**Comment by german-one** [comment]
I would have considered to leave it as is because the disabled button implies that the location can't be determined. However, I can take on the task of writing the few lines of code to inform the user 😊

**Pull request closed without merging**
